; AcornPad Build 1.0.9
; Acorn BBC Mode 4 (320 x 256 Pixels, 2  Colours)

; Charset data...
; 14 images, 8 bytes per image, total size is 112 bytes.

.char_sprite_0
    EQUB $7E ; .######.
    EQUB $66 ; .##..##.
    EQUB $66 ; .##..##.
    EQUB $E6 ; ###..##.
    EQUB $E6 ; ###..##.
    EQUB $E6 ; ###..##.
    EQUB $FE ; #######.
    EQUB $00 ; ........

.char_sprite_1
    EQUB $18 ; ...##...
    EQUB $18 ; ...##...
    EQUB $18 ; ...##...
    EQUB $38 ; ..###...
    EQUB $38 ; ..###...
    EQUB $38 ; ..###...
    EQUB $38 ; ..###...
    EQUB $00 ; ........

.char_sprite_2
    EQUB $FE ; #######.
    EQUB $C6 ; ##...##.
    EQUB $06 ; .....##.
    EQUB $FE ; #######.
    EQUB $E0 ; ###.....
    EQUB $E0 ; ###.....
    EQUB $FE ; #######.
    EQUB $00 ; ........

.char_sprite_3
    EQUB $FE ; #######.
    EQUB $06 ; .....##.
    EQUB $06 ; .....##.
    EQUB $3E ; ..#####.
    EQUB $0E ; ....###.
    EQUB $0E ; ....###.
    EQUB $FE ; #######.
    EQUB $00 ; ........

.char_sprite_4
    EQUB $C6 ; ##...##.
    EQUB $C6 ; ##...##.
    EQUB $C6 ; ##...##.
    EQUB $FE ; #######.
    EQUB $0E ; ....###.
    EQUB $0E ; ....###.
    EQUB $0E ; ....###.
    EQUB $00 ; ........

.char_sprite_5
    EQUB $FE ; #######.
    EQUB $C6 ; ##...##.
    EQUB $C0 ; ##......
    EQUB $FE ; #######.
    EQUB $0E ; ....###.
    EQUB $0E ; ....###.
    EQUB $FE ; #######.
    EQUB $00 ; ........

.char_sprite_6
    EQUB $FE ; #######.
    EQUB $C6 ; ##...##.
    EQUB $C0 ; ##......
    EQUB $FE ; #######.
    EQUB $E6 ; ###..##.
    EQUB $E6 ; ###..##.
    EQUB $FE ; #######.
    EQUB $00 ; ........

.char_sprite_7
    EQUB $FE ; #######.
    EQUB $C6 ; ##...##.
    EQUB $0C ; ....##..
    EQUB $18 ; ...##...
    EQUB $38 ; ..###...
    EQUB $38 ; ..###...
    EQUB $38 ; ..###...
    EQUB $00 ; ........

.char_sprite_8
    EQUB $7C ; .#####..
    EQUB $64 ; .##..#..
    EQUB $64 ; .##..#..
    EQUB $FE ; #######.
    EQUB $E6 ; ###..##.
    EQUB $E6 ; ###..##.
    EQUB $FE ; #######.
    EQUB $00 ; ........

.char_sprite_9
    EQUB $FE ; #######.
    EQUB $C6 ; ##...##.
    EQUB $C6 ; ##...##.
    EQUB $FE ; #######.
    EQUB $0E ; ....###.
    EQUB $CE ; ##..###.
    EQUB $FE ; #######.
    EQUB $00 ; ........

.char_sprite_10
    EQUB $00 ; ........
    EQUB $04 ; .....#..
    EQUB $04 ; .....#..
    EQUB $04 ; .....#..
    EQUB $06 ; .....##.
    EQUB $26 ; ..#..##.
    EQUB $26 ; ..#..##.
    EQUB $3E ; ..#####.

.char_sprite_11
    EQUB $00 ; ........
    EQUB $24 ; ..#..#..
    EQUB $24 ; ..#..#..
    EQUB $24 ; ..#..#..
    EQUB $3E ; ..#####.
    EQUB $32 ; ..##..#.
    EQUB $32 ; ..##..#.
    EQUB $32 ; ..##..#.
    
.char_sprite_12
    EQUB $00 ; ........
    EQUB $3E ; ..#####.
    EQUB $22 ; ..#...#.
    EQUB $22 ; ..#...#.
    EQUB $22 ; ..#...#.
    EQUB $22 ; ..#...#.
    EQUB $2E ; ..#..##.
    EQUB $3E ; ..#####.

.char_sprite_13
    EQUB $00 ; ........
    EQUB $3E ; ..#####.
    EQUB $20 ; ..#.....
    EQUB $20 ; ..#.....
    EQUB $3E ; ..#####.
    EQUB $06 ; .....##.
    EQUB $06 ; .....##.
    EQUB $3E ; ..#####.

.char_sprite_14
    EQUB $00 ; ........
    EQUB $3E ; ..#####.
    EQUB $22 ; ..#...#.
    EQUB $22 ; ..#...#.
    EQUB $3E ; ..#####.
    EQUB $30 ; ..##....
    EQUB $30 ; ..##....
    EQUB $30 ; ..##....

.char_sprite_15
    EQUB $00 ; ........
    EQUB $00 ; ........
    EQUB $00 ; ........
    EQUB $00 ; ........
    EQUB $00 ; ........
    EQUB $00 ; ........
    EQUB $00 ; ........
    EQUB $00 ; ........
   
.char_sprite_16
    EQUB $10 ; ...#....
    EQUB $10 ; ...#....
    EQUB $10 ; ...#....
    EQUB $10 ; ...#....
    EQUB $10 ; ...#....
    EQUB $10 ; ...#....
    EQUB $10 ; ...#....
    EQUB $00 ; ........
    
.char_sprite_17
    EQUB $14 ; ...#.#..
    EQUB $14 ; ...#.#..
    EQUB $14 ; ...#.#..
    EQUB $14 ; ...#.#..
    EQUB $14 ; ...#.#..
    EQUB $14 ; ...#.#..
    EQUB $14 ; ...#.#..
    EQUB $00 ; ........
    
.char_sprite_18
    EQUB $00 ; ........
    EQUB $18 ; ...##...
    EQUB $18 ; ...##...
    EQUB $00 ; ........
    EQUB $18 ; ...##...
    EQUB $18 ; ...##...
    EQUB $00 ; ........
    EQUB $00 ; ........

.char_sprite_19
    EQUB $00 ; ........
    EQUB $3E ; ..#####.
    EQUB $77 ; .###.###
    EQUB $77 ; .###.###
    EQUB $7F ; .#######
    EQUB $77 ; .###.###
    EQUB $00 ; ........
    EQUB $00 ; ........

.char_sprite_20
    EQUB $00 ; ........
    EQUB $7E ; .######.
    EQUB $77 ; .###.###
    EQUB $77 ; .###.###
    EQUB $77 ; .###.###
    EQUB $7E ; .######.
    EQUB $00 ; ........
    EQUB $00 ; ........

.char_sprite_21
    EQUB $00 ; ........
    EQUB $7F ; .#######
    EQUB $70 ; .###....
    EQUB $7E ; .######.
    EQUB $70 ; .###....
    EQUB $7F ; .#######
    EQUB $00 ; ........
    EQUB $00 ; ........

.char_sprite_22
    EQUB $00 ; ........
    EQUB $3F ; ..######
    EQUB $70 ; .###....
    EQUB $77 ; .###.###
    EQUB $77 ; .###.###
    EQUB $3F ; ..######
    EQUB $00 ; ........
    EQUB $00 ; ........

.char_sprite_23
    EQUB $00 ; ........
    EQUB $70 ; .###....
    EQUB $70 ; .###....
    EQUB $70 ; .###....
    EQUB $70 ; .###....
    EQUB $7F ; .#######
    EQUB $00 ; ........
    EQUB $00 ; ........

.char_sprite_24
    EQUB $00 ; ........
    EQUB $63 ; .##...##
    EQUB $77 ; .###.###
    EQUB $7F ; .#######
    EQUB $6B ; .##.#.##
    EQUB $63 ; .##...##
    EQUB $00 ; ........
    EQUB $00 ; ........

.char_sprite_25
    EQUB $00 ; ........
    EQUB $67 ; .##..###
    EQUB $77 ; .###.###
    EQUB $7F ; .#######
    EQUB $77 ; .###.###
    EQUB $73 ; .###..##
    EQUB $00 ; ........
    EQUB $00 ; ........

.char_sprite_26
    EQUB $00 ; ........
    EQUB $3E ; ..#####.
    EQUB $77 ; .###.###
    EQUB $77 ; .###.###
    EQUB $77 ; .###.###
    EQUB $3E ; ..#####.
    EQUB $00 ; ........
    EQUB $00 ; ........

.char_sprite_27
    EQUB $00 ; ........
    EQUB $7E ; .######.
    EQUB $77 ; .###.###
    EQUB $77 ; .###.###
    EQUB $7E ; .######.
    EQUB $77 ; .###.###
    EQUB $00 ; ........
    EQUB $00 ; ........

.char_sprite_28
    EQUB $00 ; ........
    EQUB $77 ; .###.###
    EQUB $77 ; .###.###
    EQUB $77 ; .###.###
    EQUB $36 ; ..##.##.
    EQUB $1C ; ...###..
    EQUB $00 ; ........
    EQUB $00 ; ........

.char_sprite_29
    EQUB $00 ; ........
    EQUB $63 ; .##...##
    EQUB $6B ; .##.#.##
    EQUB $7F ; .#######
    EQUB $77 ; .###.###
    EQUB $63 ; .##...##
    EQUB $00 ; ........
    EQUB $00 ; ........

.char_sprite_31
    EQUB $00 ; ........
    EQUB $00 ; ........
    EQUB $00 ; ........
    EQUB $FF ; ########
    EQUB $FF ; ########
    EQUB $00 ; ........
    EQUB $00 ; ........
    EQUB $00 ; ........

.char_sprite_32
    EQUB $18 ; ...##...
    EQUB $18 ; ...##...
    EQUB $18 ; ...##...
    EQUB $18 ; ...##...
    EQUB $18 ; ...##...
    EQUB $18 ; ...##...
    EQUB $18 ; ...##...
    EQUB $18 ; ...##...

.char_sprite_33
    EQUB $00 ; ........
    EQUB $00 ; ........
    EQUB $00 ; ........
    EQUB $0F ; ....####
    EQUB $17 ; ...#.###
    EQUB $18 ; ...##...
    EQUB $18 ; ...##...
    EQUB $18 ; ...##...

.char_sprite_34
    EQUB $00 ; ........
    EQUB $00 ; ........
    EQUB $00 ; ........
    EQUB $F0 ; ####....
    EQUB $E8 ; ###.#...
    EQUB $18 ; ...##...
    EQUB $18 ; ...##...
    EQUB $18 ; ...##...

.char_sprite_35
    EQUB $18 ; ...##...
    EQUB $18 ; ...##...
    EQUB $18 ; ...##...
    EQUB $17 ; ...#.###
    EQUB $0F ; ....####
    EQUB $00 ; ........
    EQUB $00 ; ........
    EQUB $00 ; ........

.char_sprite_36
    EQUB $18 ; ...##...
    EQUB $18 ; ...##...
    EQUB $18 ; ...##...
    EQUB $E8 ; ###.#...
    EQUB $F0 ; ####....
    EQUB $00 ; ........
    EQUB $00 ; ........
    EQUB $00 ; ........





